### ISSUE TITLE
[Tracker] enable critical project to function by temporay fix of storages

### ISSUE THREAD

**Issue by harshad16** [operate-first/apps#2064]
As there is an access issue going on for the object bucket claim, issue: [object storage incident](https://github.com/operate-first/support/issues/648)

Multiple critical projects are affected by this, try temporary fixes to get them available.
- [x] Prow CI (opf-ci-prow): move the object storage to morty
- [x] image-registry (openshift-image-registry): move the object storage to morty
- [x] loki(opf-observatorium): move the object storage to morty

**Comment by durandom** [comment]
@harshad16 @HumairAK IIRC the storage issue with smaug has been resolved. Can we move the object storage, now that morty is down?
Would it be enough to just revert the PRs linked here?

**Comment by harshad16** [comment]
Depends if the storage bucket are same in the smaug cluster, if they were not changed, then yes :)

**Comment by harshad16** [comment]
With Morty being decommissioned, all the obc are back on smaug cluster.
This is no longer needed.
Thanks to everyone who worked on this.
