### ISSUE TITLE
[EPIC] Replicate NERC ACM-based monitoring Stack in Operate-first

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/apps#2270]
A priority for operate-first is to make our alerting, logging and monitoring stack easier to manage, and so we have decided to replicate what NERC has for their logging and monitoring stack in operate-first. The objectives are as follows:
- [x] upgrade infra cluster to 4.9 --> 4.10  [@Gregory-Pereira ]
- [x] upgrade RHACM to 2.5.1 [@Gregory-Pereira]
- [ ] Setup Storage on infra-cluster [@tumido]
- [ ] Setup NERC observabillity [@HumairAK]
/cc @durandom
