### ISSUE TITLE
[EPIC] - Os-cimate cluster 2 resource usage optimizing needed

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#2485]
Context: https://github.com/operate-first/support/issues/1104

Kepler generates a lot of data, very fast. Promtheus (UWM) was unable to keep up via remote write. Producer could not keep up (its resource was also not bounded via limits). Kafka buffer was bottlenecked. 

We have currently stopped pushing metrics from prometheus to kafka.

Immediate Action items:
- [ ] Supply analysis of what happened in https://github.com/operate-first/support/issues/1104 
    * Parse through monitoring/logs/events any historical record/proof describing root causes (e.g. disk pressure)
    * Figure out how to connect to 'my-cluster' kafka instances, and check how many messages exist in the topics (and if there are messages that have not been consumed). Is consumer actually consuming the messages? (@HumairAK) 
    * Is trino acting as a consumer for kafka? do these messages configured by trino get stored somewhere indefinitely? where? (@bryonbaker)

- [ ] Kafka needs to be optimized: 
    * Kafka should not be ephemeral. Otherwise Kafka results in hogging up node fs storage, because it will start storing messages on pod (node) disk.  
    * Do we need replication?
    * Give kafka cluster a proper name 
    * External route/access needed? 
- [ ] CPU / Memory limits on everything. E.g. producer/kafka/etc. (@HumairAK)
- [ ] Double check kepler metrics are being recorded in prometheus, and confirm cardinality is reasonable (@redmikhail) 
- [ ] UWM prometheus pods should be running on Infra cluster nodes 

Long term action items: 
-  Whole design of kepler -> prometheus -> producer -> kafka -> trino seems not optimal at all, and should be revisited (@redmikhail  / @caldeirav ) 
- Monitoring / Alerting implementation needs to be considered.
