### ISSUE TITLE
[EPIC] Categorical encoding JH notebooks deployment 

### ISSUE THREAD

**Issue by tumido** [operate-first/apps#600]
This is a master task for categorical encoding JH images deployment within the Operate First CD. The aim is to have a fully transparent, open source, deterministic deployment of a selected usecase.

Steps:
- [x] Set up a build pipeline for the public image https://github.com/aicoe-aiops/categorical-encoding/issues/2
- [x] Pushing JH images to public quay https://github.com/aicoe-aiops/categorical-encoding/issues/2
- [x] ~~Deploying the build pipeline on operated-first cluster (not now)~~
- [x] Pulling it to operated-first JH https://github.com/operate-first/continuous-deployment/issues/30
- [ ] Cloning data to operated-first cluster https://github.com/operate-first/continuous-deployment/issues/28
- [ ] Exposing the data to spark/Hue https://github.com/operate-first/continuous-deployment/issues/29
- [ ] Packaging automating Superset dashboard creation on the operated-first cluster  https://github.com/operate-first/continuous-deployment/issues/29

**Comment by tumido** [comment]
Stale, can be closed now.
